language: objective-c
os: osx
osx_image: xcode9.3

env:
  global:
  - IOS_SCHEME="Nuke iOS"
  - MACOS_SCHEME="Nuke macOS"
  - TVOS_SCHEME="Nuke tvOS"
  - WATCHOS_SCHEME="Nuke watchOS"

  matrix:
  - DESTINATION="OS=11.3,name=iPhone X"
    SCHEME="$IOS_SCHEME"     RUN_TESTS="YES"
  - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"
    SCHEME="$IOS_SCHEME"     RUN_TESTS="YES"
  - DESTINATION="OS=9.3,name=iPhone 5"
    SCHEME="$IOS_SCHEME"     RUN_TESTS="YES"

  - DESTINATION="OS=11.3,name=Apple TV 4K"
    SCHEME="$TVOS_SCHEME"    RUN_TESTS="YES"

  - DESTINATION="arch=x86_64"
    SCHEME="$MACOS_SCHEME"   RUN_TESTS="YES"

  - DESTINATION="OS=4.3,name=Apple Watch - 42mm"
    SCHEME="$WATCHOS_SCHEME" RUN_TESTS="NO"
  - DESTINATION="OS=3.2,name=Apple Watch - 42mm"
    SCHEME="$WATCHOS_SCHEME" RUN_TESTS="NO"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug | xcpretty;
    else
      xcodebuild build -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug | xcpretty;
    fi
