language: objective-c
os: osx

git:
  depth: 1

env:
  global:
    - SCHEME="Nuke"

matrix:
  include:
    - osx_image: xcode10.2
      env: DESTINATION="OS=12.2,name=iPhone X" RUN_TESTS="YES" SWIFT_VERSION="5.0"
    - osx_image: xcode10.2
      env: DESTINATION="OS=12.1,name=iPhone X" RUN_TESTS="YES" SWIFT_VERSION="5.0"
    - osx_image: xcode10.2
      env: DESTINATION="OS=12.0,name=iPhone X" RUN_TESTS="YES" SWIFT_VERSION="5.0"
    - osx_image: xcode10.2
      env: DESTINATION="OS=11.4,name=iPhone X" RUN_TESTS="YES" SWIFT_VERSION="5.0"
    - osx_image: xcode10.2
      env: DESTINATION="OS=11.0.1,name=iPhone X" RUN_TESTS="YES" SWIFT_VERSION="5.0"
    - osx_image: xcode10.2
      env: DESTINATION="OS=10.3.1,name=iPhone SE" RUN_TESTS="YES" SWIFT_VERSION="5.0"

    - osx_image: xcode10.2
      env: DESTINATION="OS=12.2,name=iPhone X" RUN_TESTS="YES" SWIFT_VERSION="4.2"
    - osx_image: xcode10.2
      env: DESTINATION="OS=11.4,name=iPhone X" RUN_TESTS="YES" SWIFT_VERSION="4.2"
    - osx_image: xcode10.2
      env: DESTINATION="OS=10.3.1,name=iPhone SE" RUN_TESTS="YES" SWIFT_VERSION="4.2"

    - osx_image: xcode10.1
      env: DESTINATION="OS=11.4,name=iPhone X" RUN_TESTS="YES" SWIFT_VERSION="4.2"

    - osx_image: xcode10.2
      env: DESTINATION="OS=12.2,name=Apple TV 4K" RUN_TESTS="YES" SWIFT_VERSION="5.0"
    - osx_image: xcode10.2
      env: DESTINATION="OS=11.3,name=Apple TV 4K" RUN_TESTS="YES" SWIFT_VERSION="5.0"

    - osx_image: xcode10.2
      env: DESTINATION="arch=x86_64" RUN_TESTS="YES" SWIFT_VERSION="5.0"

    - osx_image: xcode10.2
      env: DESTINATION="OS=4.2,name=Apple Watch - 42mm" RUN_TESTS="NO" SWIFT_VERSION="5.0"
    - osx_image: xcode10.2
      env: DESTINATION="OS=3.2,name=Apple Watch - 42mm" RUN_TESTS="NO" SWIFT_VERSION="5.0"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug SWIFT_VERSION="$SWIFT_VERSION" | xcpretty;
    else
      xcodebuild build -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug SWIFT_VERSION="$SWIFT_VERSION" | xcpretty;
    fi
